### ISSUE TITLE
Sync doesn't work when package contains uncommon chars

### ISSUE THREAD

**Issue by matthias-ebner** [heikkipora/registry-sync#25] opened 2019-11-18 11:02 UTC
Tested it with the following package:

`"@csstools/normalize.css": {
      "version": "9.0.1",
      "resolved": "https://registry.npmjs.org/@csstools/normalize.css/-/normalize.css-9.0.1.tgz",
      "integrity": "sha512-6It2EVfGskxZCQhuykrfnALg7oVeiI6KclWSmGDqB0AiInVrTGB9Jp9i4/Ad21u9Jde/voVQz6eFX/eSg/UsPA=="
    },`

Seems that the combination of forward slash and dot in the name causes the sync to abort.

**Comment by heikkipora** [comment] 2019-11-23 12:55
How did it not work?
registry-sync's test suite verifies that namespaced packages with dots in the name work.

**Comment by heikkipora** [comment] 2019-11-24 09:25
The sync problem was very likely caused by an npm registry metadata issue mentioned in this PR: https://github.com/heikkipora/registry-sync/pull/24

Closing this issue.

**Closed by heikkipora** 2019-11-24 09:25 UTC
